update dead links
RasaHQ/rasa pull request #10558
Opened 2021-12-20 16:18 UTC by carlad

**Proposed changes**:
These are minor changes to documentation that fix a few dead links following the release of Rasa Enterprise 1.0

2021-12-20 16:35 UTC, m-vdb requested changes

2021-12-20 16:35 UTC, m-vdb commented on docs/docs/tuning-your-model.mdx
> +and [Prediction](https://rasa.com/docs/rasa/reference/rasa/core/policies/policy#policyprediction-objects) objects, which contain
same as above, what's wrong?

2021-12-20 16:35 UTC, m-vdb commented on docs/docs/training-data-importers.mdx
> +[`TrainingDataImporter`](https://rasa.com/docs/rasa/reference/rasa/shared/importers/importer):
what's wrong with this link? the local URI should work 🤔

2021-12-20 16:36 UTC, m-vdb commented
@carlad I don't think that this PR fixes the error you had [here](https://github.com/RasaHQ/rasa/runs/4583863881?check_suite_focus=true#step:11:166) 🤔

2021-12-21 09:50 UTC, carlad commented
> @carlad I don't think that this PR fixes the error you had [here](https://github.com/RasaHQ/rasa/runs/4583863881?check_suite_focus=true#step:11:166) 🤔

That error doesn't appear on `main` as the `docs/how-to-deploy.mdx` page no longer exists.

2021-12-21 13:54 UTC, closed without merging