10823 update slack installation doc
RasaHQ/rasa pull request #10940
Opened 2022-02-23 15:28 UTC by sanchariGr

**Proposed changes**:
- As a fix for this [Issue](https://github.com/RasaHQ/rasa/issues/10823#event-6075321987), there is a small update that was needed to the docs.

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [x] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/main/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

2022-02-23 15:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RasaHQ/rasa?pullRequest=10940) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RasaHQ/rasa?pullRequest=10940) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RasaHQ/rasa?pullRequest=10940) it.</sub>

2022-02-23 15:34 UTC, ancalita reviewed
Looks great 🙌🏼 Could you also add a `doc` changelog entry, guidelines are here: https://github.com/RasaHQ/rasa/blob/main/changelog/README.md

2022-02-23 15:36 UTC, sanchariGr commented
> Looks great 🙌🏼 Could you also add a `doc` changelog entry, guidelines are here: https://github.com/RasaHQ/rasa/blob/main/changelog/README.md

sorry missed that, on it 👍

2022-02-23 21:29 UTC, melindaloubser1 requested changes
From the issue, do we need to add more permissions to the end of the section too?

2022-02-23 21:29 UTC, melindaloubser1 commented on changelog/10940.doc.md
> +addiotional step is needed to allow direct messages to the bot.
```suggestion
additional step is needed to allow direct messages to the bot.
```

2022-02-23 21:29 UTC, melindaloubser1 commented on docs/docs/connectors/slack.mdx
> +3. Configure the webhook by heading to **Event Subscriptions** and
```suggestion
2. To send messages directly to your bot using the slack UI, head to **App Home**,
   scroll to the bottom and select the checkbox for
   `Allow users to send Slash commands and messages from the messages tab.`

   You might have to quit the Slack app and re-open it before your changes take effect.

   <Image img={appHomeImg} caption="Messages Tab" alt="Allow users to send Slash commands and messages from the messages tab" max-width="500px"/>

3. Configure the webhook by heading to **Event Subscriptions** and
```

2022-02-24 08:09 UTC, sanchariGr commented
> From the issue, do we need to add more permissions to the end of the section too?

@melindaloubser1 I tried both with and without the added permissions mentioned in the issue and it worked both times so i believe whatever was causing this was fixed by slack themselves, and so we dont need to add any other permissions.

2022-02-24 10:36 UTC, melindaloubser1 approved these changes

2022-02-24 12:39 UTC, merged

2022-02-25 10:51 UTC, m-vdb commented
woot woot first PR on Open Source @sanchariGr 🎉