Update server.py
RasaHQ/rasa pull request #11308
Opened 2022-07-07 09:49 UTC by ChineseZheng

On line 1493-1501.Fiexd a problem "Ran training, but it finished without a trained model” "
RASA use .yml to train data by default ,but 2.8.x use .md instead.
It will cause an train format error when using API to train data.

**Proposed changes**:
- ...

**Status (please check what you already did)**:
- [x] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/main/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

2022-07-07 09:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RasaHQ/rasa?pullRequest=11308) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RasaHQ/rasa?pullRequest=11308) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RasaHQ/rasa?pullRequest=11308) it.</sub>

2022-07-20 10:57 UTC, melindaloubser1 requested changes
Thanks for the PR! Can you undo the many file deletions that have been committed?

2022-07-20 10:57 UTC, melindaloubser1 commented on rasa/server.py
>          rasa.shared.utils.io.write_text_file(
Please update the docstring to match the change

2023-07-31 16:53 UTC, radovanZRasa commented
Stale PR. Closing.

2023-07-31 16:53 UTC, closed without merging