Rename entity extractor mixin
RasaHQ/rasa pull request #11356
Opened 2022-07-18 22:19 UTC by VitorLamego

Co-authore-by: AlGouvea <alvarohsgouvea@gmail.com>

**Proposed changes**:
- As proposed in the https://github.com/RasaHQ/rasa/issues/10225 references of EntityExtractorMixin were renamed to EntityExtractor for consistency.

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/main/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

2022-07-20 09:54 UTC, melindaloubser1 requested changes
Thanks for addressing this!
The [migration guide in the docs](https://github.com/RasaHQ/rasa/blob/main/docs/docs/migration-guide.mdx#changes-to-custom-nlu-components) should also be updated to indicate the change. Since the migration will differ for users before and after the rename, I'd suggest adding a callout like e.g.
```
:::info Changed in 3.3

As of 3.3, the `EntityExtractorMixin` has been renamed back to `EntityExtractor`. The migration instructions below are valid for versions >= 3.0, <3.3.

:::

```

2022-08-02 13:53 UTC, melindaloubser1 approved these changes
🚀

2022-08-02 13:54 UTC, melindaloubser1 commented on changelog/10225.improvement.md
> +Rename `EntityExtractorMixin` to `EntityExtractor` due to consistency, as it was discussed in issue 10225.
```suggestion
Rename `EntityExtractorMixin` to `EntityExtractor` for consistency, as was discussed in issue 10225.
```
a nitpick =)

2022-08-03 12:06 UTC, melindaloubser1 commented
Since I can't push to your fork, there's a branch & commit here with the suggested changes - could you pull these into your branch?
https://github.com/RasaHQ/rasa/commit/b1401df095049b04c230fbf0005a306ee39eb144

2022-08-04 19:23 UTC, VitorLamego commented
Done!

2022-08-04 20:44 UTC, melindaloubser1 approved these changes

2022-08-04 21:46 UTC, melindaloubser1 commented
Thanks, do you mind addressing the[ failing CI checks](https://github.com/RasaHQ/rasa/runs/7680562006?check_suite_focus=true) ? They're my fault, I added the logging module when testing locally.
The documentation check is failing because of a flaky link, don't worry about that one.

2022-08-09 14:15 UTC, VitorLamego commented
No problem! Is there any way I could help on documentation check ?? @melindaloubser1

2022-08-09 14:17 UTC, melindaloubser1 commented
There was a PR to make the check non-required here: https://github.com/RasaHQ/rasa/pull/11413 - the commit is also on `main`, so if you merge main into your branch, it should take care of it.

2022-08-10 12:30 UTC, melindaloubser1 commented
Last failing check here https://github.com/RasaHQ/rasa/runs/7748482684?check_suite_focus=true you can fix it by running `make formatter`

2022-08-15 15:36 UTC, melindaloubser1 commented
@VitorLamego I'm so sorry, now there's conflicts that have to be resolved - I'll try make sure this time once that's done this gets merged quickly so it doesn't get into a conflict state again

2022-08-16 01:37 UTC, VitorLamego commented
Done @melindaloubser1 !

2022-08-16 08:21 UTC, melindaloubser1 requested changes

2022-08-16 08:21 UTC, melindaloubser1 commented on docs/docs/migration-guide.mdx
> +The `ConcurrentRedisLockStore` recreates the `TicketLock` from the persisted `Ticket` instances, which allows it to handle concurrent messages for the same conversation ID.
```suggestion
```

2022-08-16 08:21 UTC, melindaloubser1 commented on docs/docs/migration-guide.mdx
> +The `ConcurrentRedisLockStore` recreates the `TicketLock` from the persisted `Ticket` instances, which allows it to handle concurrent messages for the same conversation ID.
This got in here by a matter of unfortunate timing - it's not in main anymore so it shouldn't be added

2022-08-18 15:37 UTC, VitorLamego commented
Everything ok ? @melindaloubser1

2022-08-19 15:53 UTC, ancalita approved these changes
@VitorLamego Approving this as Melinda is no longer a maintainer for this repo.
Please run `make formatter` to resolve the formatting check fail. Before that ensure that the version of `black` in your venv is `22.6.0`.
Also you can run `make lint` and `make types` to check for any additional errors that this Code quality check could uncover and fix them before committing.

2022-09-11 04:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RasaHQ/rasa?pullRequest=11356) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/RasaHQ/rasa?pullRequest=11356) before we can accept your contribution.<br/>**5** out of **6** committers have signed the CLA.<br/><br/>:white_check_mark: SamuelNoB<br/>:white_check_mark: AlGouvea<br/>:white_check_mark: VitorLamego<br/>:white_check_mark: thiagohdaqw<br/>:white_check_mark: melindaloubser1<br/>:x: RochaCarla<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RasaHQ/rasa?pullRequest=11356) it.</sub>

2022-09-11 04:54 UTC, VitorLamego commented
Sorry for the delay! I believe it is ok now :) @ancalita

2022-09-12 11:46 UTC, ancalita requested changes
Looks good 👍🏻 
A few things need ironing out before merging, please address the comments below 🙏🏻

2022-09-12 11:46 UTC, ancalita commented on docs/docs/migration-guide.mdx
> +### ConcurrentRedisLockStore
Not entirely sure how this section ended up here, maybe you merged an old version of `main` into your branch, however this needs to be removed (Lines 18 - 43 inclusive).

2022-09-12 11:46 UTC, ancalita commented on rasa/nlu/extractors/extractor.py
> +    def __init_subclass__(cls, **kwargs):
Code Quality check failed because the parameters in this method need to have type hints. Please add them, kwargs can be of type `Any`.

2022-09-14 14:44 UTC, VitorLamego commented
It seems that errors on CI are not due to this issue, right ?? Anything else we could do to help ? @ancalita

2022-09-21 15:38 UTC, ancalita commented
> It seems that errors on CI are not due to this issue, right ?? Anything else we could do to help ? @ancalita

I've restarted the jobs, could have been flaky incidents.

2022-12-14 20:37 UTC, AlvaroLeles requested changes

2022-12-14 20:37 UTC, AlvaroLeles commented on rasa/nlu/extractors/extractor.py
> +    def __init_subclass__(cls, **kwargs: Any):
```suggestion
    def __init_subclass__(cls: EntityExtractor, **kwargs: Any):
```

2023-02-08 20:52 UTC, closed without merging