Add pull_request_target for fork PRs
RasaHQ/rasa pull request #11655
Opened 2022-10-12 14:43 UTC by miraai

**Proposed changes**:
- ...

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/main/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

2022-10-12 15:11 UTC, rasa-jmac reviewed
This looks good to me from a first pass.

I think we can simplify the build/push logic (lines 664 onwards) because they were originally split out from a "build + push" step into "build" and "push if not a fork" in the first attempt to solve this problem. If this all looks like it works we can refactor it back into how it was before: https://github.com/RasaHQ/rasa/pull/11590/files

2022-10-13 15:37 UTC, rasa-jmac commented on .github/workflows/continous-integration.yml
> +          docker buildx bake --set *.platform=linux/amd64 -f docker/docker-bake.hcl base --push
```suggestion
          docker buildx bake -f docker/docker-bake.hcl base --push
```

2022-10-13 15:37 UTC, rasa-jmac commented on .github/workflows/continous-integration.yml
> +          docker buildx bake --set *.platform=linux/arm64 -f docker/docker-bake.hcl base --push
```suggestion

```

2022-10-13 15:44 UTC, rasa-jmac requested changes
This looks good to me, I like how you've cleaned up the conditions.

I realise now the PR I linked you to as a reference had different architecture builds for the Docker images but that was a test that didn't go anywhere unrelated to the PR. For each of the Docker build steps, we can just include one `docker buildx --push` command instead of the two for each architecture, eg:

```
docker buildx bake -f docker/docker-bake.hcl base
```

instead of the two architectures:
```
 docker buildx bake --set *.platform=linux/amd64 -f docker/docker-bake.hcl base --push
 docker buildx bake --set *.platform=linux/arm64 -f docker/docker-bake.hcl base --push
```

Does that make sense?

2022-10-13 16:14 UTC, rasa-jmac commented
Also, I wonder if we should change the label from `status:fork` to something more explicit that a dev would be less likely to add by accident like `security-review:done` or `dangerous:acknowledged`

2022-10-13 16:32 UTC, miraai commented
> Also, I wonder if we should change the label it needs from `status:fork` to something more explicit that a dev would be less likely to add by accident like `security-review:done` or `privileged:yes`

Oh yeah, definitely. I used `status:fork` more like a placeholder until we agree on a label name.

2022-10-14 13:25 UTC, rasa-jmac reviewed
Looks good except one condition where it looks like you've swapped the logic

2022-10-14 14:16 UTC, miraai commented on .github/workflows/continous-integration.yml
> +        if: env.IS_TAG_BUILD && (github.event_name == 'pull_request' || env.IS_PULL_REQUEST_TARGET_FORK == 'true')
Good catch, that wasn't on purpose, probably missed it when i was rewriting it. Thanks!

2022-10-14 14:25 UTC, rasa-jmac approved these changes
LGTM!

2022-10-25 13:47 UTC, rasa-jmac approved these changes
LGTM!

2022-10-25 13:52 UTC, merged