doc: add testing story example for button with payload
RasaHQ/rasa pull request #11766
Opened 2022-11-16 07:02 UTC by porti20

**Proposed changes**:
- Clearify in the documentation how to write testing stories if a user press a button with payload

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [x] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/main/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

2022-11-16 07:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RasaHQ/rasa?pullRequest=11766) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RasaHQ/rasa?pullRequest=11766) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RasaHQ/rasa?pullRequest=11766) it.</sub>

2022-11-18 10:16 UTC, ancalita requested changes
@porti20 Thank you for contribution 💯 Left two suggestions which should be addressed for approval.

2022-11-18 10:16 UTC, ancalita commented on changelog/11766.doc.md
> +Clearify in the documentation how to write testing stories if a user press a button with payload
```suggestion
Clarify in the documentation how to write testing stories if a user presses a button with payload.
```

2022-11-18 10:16 UTC, ancalita commented on docs/docs/testing-your-assistant.mdx
> +  ```yaml-rasa title="tests/test_stories.yml" {5,12}
I think here you'd like to highlight lines 8, 11 which contain the user examples for handling buttons.
```suggestion
  ```yaml-rasa title="tests/test_stories.yml" {8,11}
```

2022-11-18 10:43 UTC, porti20 commented
@ancalita Thanks for your review, i accepted you changes :)

2022-11-18 11:54 UTC, ancalita approved these changes
🚀

2022-11-18 11:55 UTC, merged