Fix some grammar errors and redundant words
RasaHQ/rasa pull request #11984
Opened 2023-01-31 14:05 UTC by italovinicius18

Co-authored-by: IanFPFerreira <ianfillipe@gmail.com>
Co-authored-by: guilhermemoraisr <guilhermemoraisr@gmail.com>

**Proposed changes**:
- There were words and spaces that were duplicated and some wrong syntax that was corrected

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [X] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/main/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

2023-01-31 14:09 UTC, italovinicius18 commented
@m-vdb I continued the work on the errors related to this issue #10954 and reviewed the docs again for errors, so I am making this PR, because some errors passed me by

2023-02-01 15:03 UTC, m-vdb requested changes
Thanks a lot @PedroLucasCM for fixing the docs 🙌🏻 I think there were 2 mistakes, can you address them?

2023-02-01 15:03 UTC, m-vdb commented on docs/docs/action-server/actions.mdx
> -A response can be of any of the response types described in the
I think this form is correct

2023-02-01 15:03 UTC, m-vdb commented on docs/docs/action-server/knowledge-base-actions.mdx
> -  as `mention`. We also use synonyms to map some of the mentions to symbols. You can learn about that
I think this form is correct

2023-02-01 15:32 UTC, PedroLucasCM commented
> Thanks a lot @PedroLucasCM for fixing the docs 🙌🏻 I think there were 2 mistakes, can you address them?

Hey @m-vdb I think you mistook me for @italovinicius18 :sweat_smile: we're on the same team though and already warned him

2023-02-06 13:58 UTC, m-vdb approved these changes

2023-02-06 13:58 UTC, merged

2023-02-06 13:58 UTC, m-vdb commented
Thanks a lot @italovinicius18 🙏🏻