[ATO-663] Port solution to compress custom action request to main
RasaHQ/rasa pull request #11998
Opened 2023-02-02 15:42 UTC by radovanZRasa

**Proposed changes**:
Add capability to compress body of an HTTP request for action server

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/main/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

2023-02-03 09:33 UTC, ancalita requested changes
I've left my review on `3.2.x` PR, the comments are applicable here too.

2023-02-14 15:21 UTC, radovanZRasa commented
> I've left my review on `3.2.x` PR, the comments are applicable here too.

All comments on [Compress body of HTTP request (3.2.x)](https://github.com/RasaHQ/rasa/pull/11995) have been addressed.
All commits have been ported.

2023-02-14 16:16 UTC, ancalita approved these changes
Left some docs suggestions.

2023-02-14 16:16 UTC, ancalita commented on docs/docs/action-server/actions.mdx
> +
Missing closing info note
```suggestion
:::
```

2023-02-14 16:16 UTC, ancalita commented on docs/docs/action-server/actions.mdx
> +Rasa SDK 3.2.2, 3.3.1, 3.4.1 and onwards,
```suggestion
Rasa has the capability to compress the HTTP request body for custom actions.
By default, this option is off to keep backward compatibility with older versions of
custom action servers which did not receive the compressed body in the HTTP request for custom actions.
To enable this option, set environment variable COMPRESS_ACTION_SERVER_REQUEST to `True`.

Rasa SDK versions `3.2.2`, `3.3.1`, `3.4.1` and upwards,
```

2023-02-14 16:16 UTC, ancalita commented on docs/docs/action-server/actions.mdx
> +support both compressed and non-compressed body in HTTP request for
```suggestion
support both compressed and non-compressed body in the HTTP request for
```

2023-02-15 13:30 UTC, merged