Add support for RulePolicy requirement - [ENG 3]
RasaHQ/rasa pull request #12001
Opened 2023-02-03 16:17 UTC by varunshankar

**Proposed changes**:
- Add support for custom RulePolicy.
- Fixes https://rasahq.atlassian.net/browse/ENG-3

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/main/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

2023-02-06 16:07 UTC, twerkmeister requested changes
Hey @varunshankar, looking all good :) Can you please add a changelog? Then this can go ahead!

2023-02-06 16:22 UTC, varunshankar commented
> Hey @varunshankar, looking all good :) Can you please add a changelog? Then this can go ahead!

Thanks a lot for the review. I have updated the changelog.

2023-02-06 17:31 UTC, twerkmeister approved these changes

2023-02-06 23:53 UTC, merged

2023-02-07 14:50 UTC, m-vdb commented
@varunshankar @twerkmeister technically this change should have been made into `main` as it's a small new feature instead of a bugfix. But I agree that's arguable.