Fix CountVectorFeaturizer to train when min_df != 1
RasaHQ/rasa pull request #12098
Opened 2023-03-03 02:08 UTC by varunshankar

**Proposed changes**:
- Restrict min_df value to 1 for all attributes except TEXT.
- Fixes: https://rasahq.atlassian.net/browse/ENG-149

**Status (please check what you already did)**:
- [x] added some tests for the functionality
- [ ] updated the documentation
- [x] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/main/changelog) for instructions)
- [x] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

2023-03-03 04:28 UTC, pankaj0998 commented
Feedback:
  - The commit message "Fixes CountVectorFeaturizer to train when min_df != 1" is accurate as the code changes reflect this.
  - The code change to the CountVectorizer constructor is correct, with the min_df parameter conditionally set to 1 if the attribute is not equal to the constant TEXT.
  - The new test case is valid and covers the fix.

2023-03-03 09:51 UTC, d61h6k4 requested changes

2023-03-03 09:51 UTC, d61h6k4 commented on tests/nlu/featurizers/test_count_vectors_featurizer.py
> +
Can you please add one more test case which fails to train `CountVectorizer` without changes and it passes with changes

2023-03-10 10:54 UTC, d61h6k4 approved these changes
LGTM 🚀

2023-03-10 13:57 UTC, merged