Use langchain rather than openai to allow for configuration
RasaHQ/rasa pull request #12666
Opened 2023-07-12 14:09 UTC by tmbo

**Proposed changes**:
- configurable llm connection
- simple caching for llm calls to improve testing and development speed

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/main/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

2023-07-12 14:40 UTC, twerkmeister requested changes
see comments

2023-07-12 14:40 UTC, twerkmeister commented on rasa/utils/llm.py
> +        return custom_config
it's surprising that a different `_type` leads to all default parameters being tossed, but I guess also makes sense, many llm providers have different defaults. making a comment about this in the docs too

2023-07-12 14:43 UTC, tmbo commented on rasa/utils/llm.py
> +        custom_config["_type"] = custom_config.pop("type")
don't want to diverge to much from the langchain format - i did make the small change to support `type` as that is what we use in other places as well, e.g.
```
nlg:
  type: rasa_plus.ml.LLMRephraser
```

2023-07-13 15:06 UTC, twerkmeister approved these changes
good to go, please fix the highlighted code quality issues before merge

2023-07-13 20:59 UTC, merged