Edit docs workflow to release docs for 3.6.x
RasaHQ/rasa pull request #12993
Opened 2024-01-11 13:04 UTC by sanchariGr

**Proposed changes**:
- ...

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/main/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

2024-01-16 15:49 UTC, m-vdb requested changes
@sanchariGr not sure, but [this workflow](https://github.com/RasaHQ/rasa/actions/runs/7543134913/job/20533450956) failed with 
> fatal: No names found, cannot describe anything.

Do you have an example of this script working correctly on the CI? If not, have you tried locally?

One thing I am confuse about, is that my understanding of the `git describe` comment is that it is not performing a fetch 🤔 but am I mistaken?

2024-01-17 06:28 UTC, sanchariGr commented
@m-vdb I have the test results added in the PR description. The failure was with tag 3.5.18.
<img width="1284" alt="Screenshot 2024-01-17 at 11 46 49" src="https://github.com/RasaHQ/rasa/assets/2388088/0cb74303-0f82-49c7-8f22-e7fbf5734613">
`git fetch` fetches all the tags available in origin so it was also fetching 3.7.0 and 3.8.0a9 (see [here](https://github.com/RasaHQ/rasa/actions/runs/7058610779/job/19214539899)). 
`git describe --tags --abbrev=0 HEAD` only gets the latest tag on a branch.

2024-01-17 08:05 UTC, m-vdb commented
ok gotcha, works for me. Something very weird is happening locally when I run the command. When I run it on main, it outputs `3.6.13`, when I run it on 3.6.x, it output `3.6.15`. In both cases that's different from what you have here

2024-01-17 08:12 UTC, sanchariGr commented
Thats because this https://github.com/RasaHQ/rasa/pull/12996 was not merged into main. So main changelog also is only updated until 3.6.13. Let me merge this and check.

2024-01-17 09:56 UTC, merged