Add docs redirects
RasaHQ/rasa pull request #13054
Opened 2024-10-16 06:39 UTC by anthonydeguzman

**Proposed changes**:
Added redirects based off SEO recommendations

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/main/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

2024-10-18 08:46 UTC, m-vdb requested changes
the `main` branch on `RasaHQ/rasa` doesn't receive updates anymore; can you point to the `documentation` branch instead? Your changes will be automatically deployed once the `documentation` branch receives new commits.

2024-10-18 08:46 UTC, m-vdb commented on docs/netlify.toml
> +to = "/docs/rasa-enterprise/changelog/rasa-enterprise-changelog/"
not sure if this rule will work, it conflicts with [this one on rasa-website](https://github.com/RasaHQ/rasa-website/blob/111584e42f7a6ac8bd68dccc8a432c274c41c718/netlify.toml#L402-L404)

2024-10-18 08:46 UTC, m-vdb commented on docs/netlify.toml
> +to = "/docs/rasa-enterprise/changelog/rasa-enterprise-changelog/"
can you move all the rasa-enterprise redirects in the rasa-x repo? [here](https://github.com/RasaHQ/rasa-x/blob/main/docs/netlify.toml)

2024-10-18 08:46 UTC, m-vdb commented on docs/netlify.toml
> +to = "/docs/"
I think this rule needs to be added to [rasa-website](https://github.com/RasaHQ/rasa-website/blob/main/netlify.toml) for it to work

2024-10-18 08:46 UTC, m-vdb commented on docs/netlify.toml
> +from = "/docs/get_started_step1/"
I think this rule needs to be added to [rasa-website](https://github.com/RasaHQ/rasa-website/blob/main/netlify.toml) for it to work

2024-10-28 05:39 UTC, closed without merging

2024-10-28 05:41 UTC, anthonydeguzman commented
Tried changing the base branch looks like I messed up this pull request. I'll open a different one