Fix the EvaluationStore to match prediction and target entities
RasaHQ/rasa pull request #6419
Opened 2020-08-14 15:48 UTC by davidezanella

**Proposed changes**:
- Fix the EvaluationStore serialise method: the prediction and target entities were not aligned. Previously, they were aligned only by adding 'None' at the end of the smaller list instead of looking where they should be placed.

Practical example:
```
target entities: [
   {'text': 'hi, how are you', 'start': 0, 'end': 2, entity: 'verb' },
   {'text': 'hi, how are you', 'start': 4, 'end': 7, entity: 'noun' }
]
predicted entities: [
   {'text': 'hi, how are you', 'start': 4, 'end': 7, entity: 'noun' }
]
```

Adding 'None' at the end, as done originally, leads to wrong metrics because even the right prediction was marked as wrong.

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

2020-08-17 06:00 UTC, sara-tagger commented
Thanks for submitting a pull request 🚀 @degiz will take a look at it as soon as possible ✨

2020-08-19 15:28 UTC, davidezanella commented
@tabergma can you review this pr?

2020-08-24 14:36 UTC, degiz commented
Hey @dakshvar22 

Thanks a lot for the PR! Could you please also write a unit for the change? I believe you can use existing `tests/test_test.py` file.

2020-08-24 14:37 UTC, degiz requested changes
Hey @davidezanella

Thanks a lot for the PR! Could you please also write a unit for the change? I believe you can use existing `tests/test_test.py` file.

2020-08-26 09:19 UTC, tabergma commented
@davidezanella Thanks for addressing this. I think your concern is valid and should be fixed, but I am not sure if your method fixes the complete problem. Currently you just iterating over the gold entities to see if there are matching predicted entities and you are adding `None` in case no matching entity could be found. That way we ensure that the size of the gold end predicted entities is the same. However, i think we also need to consider the case when we have more predicted entities than gold entities. For example, you have a sentence like "Tanja is currently in Munich, but she lives in Berlin" and the annotator made a mistake and just annotate "Tanja" as `person`, but forgot to tag "Munich" and "Berlin" as `city`. However, the model predicts all three of them. If I understand your code correctly, you would just consider the gold entity "Tanja" and you would ignore the two additional entities "Munich" and "Berlin", which is not correct as those are false positive predictions in this case. What do you think?

2020-08-26 11:19 UTC, davidezanella commented
Hey @tabergma, you are right! I've fixed the code and the tests. 
Let me know what do you think about it

2020-08-27 12:21 UTC, degiz reviewed
@tabergma will review the code.

2020-09-01 07:19 UTC, tabergma commented
@davidezanella Sorry for the late reply, I was offline a couple of days. Will take a look at the PR today. Can you please resolve the conflicts in the meantime? Thanks.

2020-09-01 08:55 UTC, tabergma requested changes
Looks great 🚀  Added a few comments. Can you please also add a [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) entry? Thanks.

2020-09-01 08:55 UTC, tabergma commented on rasa/core/test.py
>      def serialise(self) -> Tuple[List[Text], List[Text]]:
This method is now very long. Can you please split it up? We could extract the entity prediction calculation into a separate method.

2020-09-01 08:55 UTC, tabergma commented on rasa/core/test.py
> +        # sklearn does not cope with lists of unequal size, nor None values
This comments seems to be a bit unrelated. I would either add it to the doc string or remove it.

2020-09-01 08:55 UTC, tabergma commented on rasa/core/test.py
> +            def compare_entities():
I would move this method out of the method `serialise` and make it private.

2020-09-01 08:55 UTC, tabergma commented on rasa/core/test.py
> +            def compare_entities():
Also can you please add some comments to the methods to make it even more clear what cases we check.

2020-09-01 08:55 UTC, tabergma commented on rasa/core/test.py
> +                        )
This could be extracted into a helper method.

2020-09-01 08:55 UTC, tabergma commented on rasa/core/test.py
> +        entity_predictions_fixed = []
Can we rename them to `aligned_entity_targets` and `aligned_entity_predictions`?

2020-09-02 06:20 UTC, tabergma approved these changes
Looks great 💯  Thanks for fixing this!

2020-09-02 06:20 UTC, tabergma commented on rasa/core/test.py
> +            i_pred, i_target = 0, 0
Minor: We try to not use abbreviations in names. I would rename this to `index_prediction` and `index_target`.

2020-09-02 06:20 UTC, tabergma commented on rasa/core/test.py
> +                cmp = self._compare_entities(
Minor: I would rename this to `comparison_result`.

2020-09-02 06:20 UTC, tabergma commented on rasa/core/test.py
> +        i_pred: int,
Minor: Rename to `index_prediction`.

2020-09-02 06:20 UTC, tabergma commented on rasa/core/test.py
> +        i_target: int,
Minor: Rename to `index_target`.

2020-09-02 06:21 UTC, tabergma commented
@degiz I think you need to update your review otherwise we are not able to merge this PR.

2020-09-02 07:16 UTC, degiz approved these changes

2020-09-02 07:16 UTC, merged