Update __init__.py
RasaHQ/rasa pull request #6585
Opened 2020-09-07 07:42 UTC by pranavdurai10

**Proposed changes**:
-Un-used variable v in loop

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

2020-09-07 07:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RasaHQ/rasa?pullRequest=6585) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RasaHQ/rasa?pullRequest=6585) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RasaHQ/rasa?pullRequest=6585) it.</sub>

2020-09-07 12:00 UTC, sara-tagger commented
Thanks for submitting a pull request 🚀 @erohmensing will take a look at it as soon as possible ✨

2020-09-08 06:10 UTC, pranavdurai10 commented
@sara-tagger @erohmensing Hey, any heads-up on my pull request?

2020-09-08 14:47 UTC, erohmensing requested changes
Please be patient for a review when submitting a PR! 

See my comment for a suggestion :)

2020-09-08 14:47 UTC, erohmensing commented on rasa/core/events/__init__.py
> +        for k in d.items():
In my opinion it's more confusing to only use the first value from a method that returns two values than to have an unused variable. what about this instead? 
```suggestion
        for k in d.keys():
```

2020-09-08 14:59 UTC, erohmensing approved these changes
thanks for your first contribution!

2020-09-10 13:11 UTC, merged