Updated Docs Links to 2.0 structure
RasaHQ/rasa pull request #6636
Opened 2020-09-10 22:26 UTC by b-quachtran

**Proposed changes**:
- Updated docs links in source to new 2.0 structure

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

2020-09-11 04:16 UTC, b-quachtran commented
Hmm, CI checks are being weird because of the updated links in the test config files. I think it's confusing the hashtag in the URL as a comment in `https://rasa.com/docs/rasa/tuning-your-model#how-to-choose-a-pipeline`. I'm going to take a look at the test script (`tests/importers/test_autoconfig.py`) and figure out what's going on.

2020-09-14 12:45 UTC, erohmensing requested changes
Looking good so far! left some comments on yours, going in and catching some you missed now :)

2020-09-14 12:45 UTC, erohmensing commented on rasa/constants.py
> +DOCS_URL_MIGRATION_GUIDE = DOCS_BASE_URL + "/migrate-from/"
This is different -- migraation guide is migrating from one version to another, migrate from is migrating from other tools to rasa

2020-09-14 12:45 UTC, erohmensing commented on rasa/cli/x.py
> +            "directory (see http://rasa.com/docs/rasa/installation#quick-installation)."
```suggestion
            "directory (see https://rasa.com/docs/rasa/command-line-interface#rasa-init)."
```

2020-09-14 12:45 UTC, erohmensing commented on data/configs_for_docs/example_for_suggested_config_after_train.yml
> +# # See https://rasa.com/docs/rasa/tuning-your-model#how-to-choose-a-pipeline for more information.
```suggestion
# # See https://rasa.com/docs/rasa/next/model-configuration#suggested-config for more information.
```

This should go for anything that is suggested by autoconfig

2020-09-14 21:41 UTC, b-quachtran commented
@erohmensing I didn't include `next/` in the URL's since I assumed that after the docs migration it won't be needed. Should it be left in for now (e.g. https://rasa.com/docs/rasa/next/custom-actions)?

2020-09-15 14:06 UTC, erohmensing commented
No, if i merged that in its definitely a mistake 🙈

2020-09-15 16:18 UTC, erohmensing approved these changes
Amazing! Thank you for helping out!

2020-09-16 08:18 UTC, merged