make storyReader::read_from_file synchronous (#6641)
RasaHQ/rasa pull request #6731
Opened 2020-09-22 08:13 UTC by kalkbrennerei

**Proposed changes**:
- make `storyReader::read_from_file` sync including it's implementations in `MarkdownStoryReader` and `YAMLStoryReader`
- in `MarkdownStoryReader` also `_process_lines`, `_add_user_messages` and `_add_e2e_messages` were changed to sync

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [x] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

2020-09-22 08:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RasaHQ/rasa?pullRequest=6731) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RasaHQ/rasa?pullRequest=6731) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RasaHQ/rasa?pullRequest=6731) it.</sub>

2020-09-22 12:00 UTC, sara-tagger commented
Thanks for opening a draft pull request 🚀If you have any questions, you can direct them to @rctatman ✨

2020-09-23 09:10 UTC, degiz requested changes
Thanks a lot for the fix! 🚀 👍 Looks great!

I've search the name `read_from_file` and found some docs references that still assume that these method is `async`:
- `docs/docs/reference/rasa/shared/core/training_data/story_reader/markdown_story_reader.md`
- `docs/docs/reference/rasa/shared/core/training_data/story_reader/yaml_story_reader.md`

I think we still need to fix both of them.

2020-09-23 10:22 UTC, degiz approved these changes
Sorry, my bad, looks like these docs are autogenerated 😄

2020-09-24 16:41 UTC, merged