Updates to the domain docs as a result of docs workshop
RasaHQ/rasa pull request #6738
Opened 2020-09-22 13:44 UTC by degiz

Changes that me and @tabergma came up with.

**Proposed changes**:
- Updates to the domain docs 

We also wanted to try a table for the Slot types, but the tables are not ready yet as described [here](https://rasa-hq.slack.com/archives/C016FLYV4QN/p1600765887085200)

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [x] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

2020-10-16 05:57 UTC, erohmensing requested changes
Thanks for the updates, and sorry for the very delayed review 😃 could you please also take a look at cleaning up the wall of text under `Slots and Conversation Behavior`?

2020-10-16 05:57 UTC, erohmensing commented on docs/docs/domain.mdx
> +add the `use_entities: []` parameter to the intent in your `Domain`
```suggestion
add the `use_entities: []` parameter to the intent in your domain
```

2020-10-16 05:57 UTC, erohmensing commented on docs/docs/domain.mdx
> +
```suggestion

```

2020-10-16 05:57 UTC, erohmensing commented on docs/docs/domain.mdx
> +Now Rasa Core needs some training stories to learn from how to handle the
```suggestion 
Rasa Open Source needs some training stories to learn from how to handle the
```

2020-10-16 05:57 UTC, erohmensing commented on docs/docs/domain.mdx
> +Available parameters are:
```suggestion

Available parameters are:
```

2020-10-16 05:57 UTC, erohmensing commented on docs/docs/domain.mdx
> +In the code below, you can see a slot class called `NumberOfPeopleSlot`.
```suggestion
The code below defines a custom slot class called `NumberOfPeopleSlot`.
```

2020-10-27 09:25 UTC, tmbo commented
@degiz do you have time to wrap this up so we can ship it in a patch?

2020-10-27 09:26 UTC, degiz commented
@tmbo yes, can do that later today. When is the ETA for the patch?

2020-10-27 09:42 UTC, tmbo commented
no eta, there are a couple smaller PRs that are lying around that we should release. just want to make sure we don't have too many stale PRs lying around - the list from github in the engineering channel is getting quite long 😂

2020-10-29 11:47 UTC, degiz commented
> could you please also take a look at cleaning up the wall of text under Slots and Conversation Behavior?

@erohmensing The text looks ok to me! Do you see problems there?

2020-11-03 10:52 UTC, erohmensing approved these changes

2020-11-03 11:58 UTC, merged