Export data from interactive learning broken
RasaHQ/rasa pull request #6879
Opened 2020-10-02 03:38 UTC by aleronupe

**Proposed changes**:
- Retrieved the file format from the path in write_stories_to_file and passed it as a param to the tracker
- Added a method in Story structure to retrieve the story steps as yaml
- Updated a method in YAMLStoryWriter to be called in the added method
- Called method to dump the story in tracker according to the retrieved format
- Resolving issue #6603 

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [x] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [x] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

2020-10-02 03:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RasaHQ/rasa?pullRequest=6879) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/RasaHQ/rasa?pullRequest=6879) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: RomuloSouza<br/>:x: aleronupe<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RasaHQ/rasa?pullRequest=6879) it.</sub>

2020-10-02 06:00 UTC, sara-tagger commented
Thanks for submitting a pull request 🚀 @koaning will take a look at it as soon as possible ✨

2020-10-02 15:50 UTC, degiz requested changes
Thanks a lot addressing the problem! 🚀 🚀 🚀 

I left comments + also wanted to ask you to write some additional unit tests that would cover the new functionality.

2020-10-02 15:50 UTC, degiz commented on rasa/core/training/interactive.py
>                  "Please provide a valid export path for the stories, e.g. 'stories.md'.",
```suggestion
                "Please provide a valid export path for the stories, e.g. 'stories.yml'.",
```

2020-10-02 15:50 UTC, degiz commented on rasa/core/training/interactive.py
>                  "Please provide a valid export path for the NLU data, e.g. 'nlu.md'.",
```suggestion
                "Please provide a valid export path for the NLU data, e.g. 'nlu.yml'.",
```

2020-10-02 15:50 UTC, degiz commented on rasa/core/training/interactive.py
> +                [".md", ".yml"],
We can use `YAML_FILE_EXTENSIONS + MARKDOWN_FILE_EXTENSIONS` from `rasa.shared.data` here.

2020-10-02 15:50 UTC, degiz commented on rasa/core/training/interactive.py
> +                [".md", ".json", ".yml"],
We can use `TRAINING_DATA_EXTENSIONS` from rasa.shared.data here.

2020-10-02 15:50 UTC, degiz commented on rasa/core/training/interactive.py
> +                        e2e=SAVE_IN_E2E, include_source=False, story_format=story_format
`include_source=False` is a default value, we can omit it.

2020-10-02 15:50 UTC, degiz commented on rasa/core/training/interactive.py
> +        story_format = RASA_YAML
`RASA_YAML` belongs to `shared.nlu.training_data.loading` package, i.e. it's NLU, not stories.
Instead we can create a writer here right away and pass it to the `tracker.export_stories`

2020-10-02 15:50 UTC, degiz commented on rasa/shared/core/trackers.py
> +        self, e2e: bool = False, include_source: bool = False, story_format: str = ""
As mentioned in the comment above, I think we can pass a writer here instead of `story_format`, and it shouldn't have a default value.

2020-10-02 15:50 UTC, degiz commented on rasa/shared/core/training_data/story_writer/yaml_story_writer.py
> +    def stories_to_yaml(
I think we should find an alternative way to append stories - `stories_to_yaml` returns a `Dict`, and shouldn't return list of story steps.

2020-10-02 19:22 UTC, aleronupe commented
Thank you for reviewing our PR @degiz !
We'll be working on these changes right away

2020-10-05 17:00 UTC, degiz commented
Hey @aleronupe 
Thanks again for addressing this issue! We want to have it in in the upcoming `2.0` release, but this PR still misses the unit tests. Could you please squash the changes and rebase them on top of the latest muster so that we can take it over?

2020-10-07 09:33 UTC, merged