fix whitespace LM tokenize issue
RasaHQ/rasa pull request #7407
Opened 2020-11-30 08:20 UTC by howl-anderson

**Proposed changes**:
- Skip token when its text can't be tokenized by LM tokenizer (for example, whitespace)

fixs #7406

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

2020-12-01 08:51 UTC, sara-tagger commented
Thanks for submitting a pull request 🚀 @rctatman will take a look at it as soon as possible ✨

2020-12-07 10:23 UTC, tmbo requested changes
looks good :+1: can you please add a test to the unit tests in tests/nlu/featurizers/test_lm_featurizer.py as well as a changelog file to changelog/?

2020-12-07 11:08 UTC, howl-anderson commented
@tmbo Sure! I will add those features in later commits.

2020-12-10 10:11 UTC, howl-anderson commented
@tmbo Please take a look

2020-12-10 10:22 UTC, tmbo approved these changes
thanks a lot for this whitespace fix - really cool :rocket:

2020-12-10 10:22 UTC, tmbo commented on changelog/7407.bugfix.md
> +Remove token when its text (for example, whitespace) can't be tokenized by LM tokenizer (from `LanguageModelFeaturizer`)
```suggestion
Remove token when its text (for example, whitespace) can't be tokenized by LM tokenizer (from `LanguageModelFeaturizer`).
```

2020-12-14 13:34 UTC, merged