add slack notification when any job fails
RasaHQ/rasa pull request #7909
Opened 2021-02-08 20:45 UTC by HotThoughts

**Proposed changes**:
- notify slack when any job in `ci-model-regression-on-schedule.yml` fails.

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/main/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

2021-02-09 08:47 UTC, HotThoughts commented
I manually[ triggered this workflow](https://github.com/RasaHQ/rasa/runs/1861515534?check_suite_focus=true). Waiting for it now.

2021-02-09 16:39 UTC, HotThoughts commented
@tczekajlo Is there a particular reason why you use `continue-on-error: true` in the workflow? This makes the result status of a job `success` even some step fails. Alternatively, I tried to use `if: always()` for a matrix job, it runs all matrix and result `failure`.

2021-02-10 13:58 UTC, tczekajlo commented
> @tczekajlo Is there a particular reason why you use `continue-on-error: true` in the workflow? This makes the result status of a job `success` even some step fails. Alternatively, I tried to use `if: always()` for a matrix job, it runs all matrix and result `failure`.

Yes, we use `continue-on-error: true` because we wanna continue training even if one of the configurations failed.

I'd suggest moving the slack notifications to the job where we run tests instead of using a separate job for taking care of the slack notifications.

2021-02-15 10:39 UTC, tczekajlo commented on .github/workflows/ci-model-regression-on-schedule.yml
> +          args: "😱 Scheduled model regression test *${{ matrix.config }}* failed. Please check out GitHub Actions: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
```suggestion
          args: "😱 Scheduled model regression test failed (confug: *${{ matrix.config }}*, dataset: *${{ matrix.dataset }}*). Please check out GitHub Actions: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
```

2021-02-16 09:06 UTC, tczekajlo requested changes

2021-02-16 09:06 UTC, tczekajlo commented on .github/workflows/ci-model-regression-on-schedule.yml
> +      - name: Notify Slack of Failure 😱
Try to use this GH action to send messages

```
  - uses: 8398a7/action-slack@v3
    with:
      status: custom
      fields: workflow,job,commit,repo,ref,author,took
      custom_payload: |
        {
          text: "Custom Field Check",
          attachments: [{
            fallback: 'fallback',
            color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
            title: `${process.env.AS_WORKFLOW}`,
            text: 'Scheduled model regression test failed',
            fields: [{
              title: 'Configuration',
              value: '${{ matrix.config }}',
              short: false
            },
            {
              title: 'Dataset',
              value: '${{ matrix.dataset }}',
              short: false
            },
            {
              title: 'GitHub Action',
              value: `https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}`,
              short: true
            }],
            actions: [{
            }]
          }]
        }
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_TEST_WEBHOOK }}
```

2021-02-16 09:15 UTC, tczekajlo requested changes

2021-02-16 09:15 UTC, tczekajlo commented on .github/workflows/ci-model-regression-on-schedule.yml
> +      - uses: 8398a7/action-slack@v3
```suggestion
      - name: Notify Slack of Failure 😱
        uses: 8398a7/action-slack@v3
```

2021-02-16 13:32 UTC, tczekajlo requested changes

2021-02-16 13:32 UTC, tczekajlo commented on .github/workflows/ci-model-regression-on-schedule.yml
> +          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_TEST_WEBHOOK }}
```suggestion
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_CI_MODEL_REGRESSION_TEST }}
```

2021-02-16 13:32 UTC, tczekajlo commented on .github/workflows/ci-model-regression-on-schedule.yml
> +  pull_request:
```suggestion
```

2021-02-18 09:23 UTC, tczekajlo approved these changes
LGTM!

2021-02-18 10:28 UTC, merged