Consistent and faster stories fingerprinting
RasaHQ/rasa pull request #8041
Opened 2021-02-24 12:39 UTC by twerkmeister

**Proposed changes**:
- fixes #4612 by introducing checkpoint names that are , instead of being random, based on relevant location information, i.e. story/rule name, position of the checkpoint in the story, intents/texts involvement the or statement
- fixes #7955, was able to reduce finger printing time for multiWOZ from 2300 seconds ~ 40 min, to 8 seconds.

The trick to the speedup is that it seems that YAML is extremely bad with serializing / deserializing big objects/strings. Like really bad. The number of operations that pyyaml and ruamel do to read and write yaml from and to strings goes up quadratically with the size. So for the fingerprinting, I avoid writing the yaml object to a string completely and instead use our own object fingerprint method. This finding also has some interesting implications for #7892. Will comment there

**Status (please check what you already did)**:
- [x] added some tests for the functionality
- [ ] updated the documentation
- [x] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/main/changelog) for instructions)
- [x] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

2021-03-01 13:33 UTC, joejuzl requested changes

2021-03-01 13:33 UTC, joejuzl commented on rasa/shared/core/training_data/story_reader/story_step_builder.py
> +        current_steps_event_counts = [str(len(s.events)) for s in self.current_steps]
Does this actually get the position in the story? Or is it just the position within the current checkpoint? i.e. of we had a story with two different OR blocks, both with the same possible intents, would the names still be globally unique?

2021-03-01 13:33 UTC, joejuzl commented on tests/shared/core/training_data/test_graph.py
> +async def test_consistent_fingerprints():
Do we have any tests that test the uniqueness of the generated checkpoint names?

2021-03-02 08:19 UTC, twerkmeister commented
Great comments @joejuzl. Will add a test that makes sure multiple or with same intents in same story will lead to unique checkpoint names.

2021-03-02 09:47 UTC, twerkmeister commented
@joejuzl really good that you caught that problem, you were right that it was just the steps from the current checkpoint. So if there were two or statements in the same story with the same intents, occurring after the same number of steps since the last checkpoint, we would get a collision. To prevent that I added the starting checkpoint names as additional info for the id hashing. Now this problem should be solved as different event sequences would always have different starting checkpoints. The first has START_CHECKPOINT, or whatever has been defined by the user, the second will have a generated one, the third will have yet another generated one based on the second generated.

Second, I am using info about the actual events instead of just the event counts. The main reason being that we don't really enforce or even advise that story names should be distinguishable apart from a note in the docs that it makes it easier to debug. So now there can still be a collision if the story name is the same, if the events before the OR statement are exactly the same, if the start checkpoint is the same, and if the involved intents and messages are the same. But in that case I would argue it is actually the same thing and it is not a wrong collision. It will lead to some training data being duplicate but I am not sure it is an actual issue

2021-03-02 09:59 UTC, tmbo commented
just saw this in my mail and had a random thought: did you cover the case where the two intents used in an `OR` are the same but have different entities?

2021-03-02 10:36 UTC, twerkmeister commented
@tmbo good point, wasn't aware that it was possible to define entities there, will look into it

2021-03-02 12:35 UTC, twerkmeister commented
So the case when two messages in the OR statement have the same intent wouldn't have been problematic. However, there would have been a collision in the case of two stories being exactly the same in every aspect except the entities used for messages in OR statements.

2021-03-03 09:16 UTC, twerkmeister commented
@joejuzl does this look good to you?

2021-03-03 09:27 UTC, joejuzl approved these changes
Nice work!

2021-03-03 13:31 UTC, merged