7005 rasa interactive cannot write non ascii character
RasaHQ/rasa pull request #8358
Opened 2021-04-01 19:18 UTC by joaoCeilandia

**Proposed changes**:
- fix #7005 

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/main/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

2021-04-02 06:00 UTC, sara-tagger commented
Thanks for submitting a pull request 🚀 @desmarchris will take a look at it as soon as possible ✨

2021-04-06 12:20 UTC, HotThoughts commented
Hey, the failing step wait for doc tests in CI workflow has fixed. The PR should be ready to review when the fix merged into your PR. 😊

2021-04-06 14:57 UTC, HotThoughts commented
Seems like the fix does not work with the situation when updating from the base branch I will fix this soon!

2021-04-08 18:02 UTC, HotThoughts commented
👋 Hey, the error is fixed. Please update the branch.

2021-04-08 18:07 UTC, joaoCeilandia commented
Thanks! @HotThoughts

2021-04-08 20:46 UTC, HotThoughts commented
@RasaHQ/enable-squad maybe one of you can review this PR?

2021-04-13 11:31 UTC, twerkmeister commented
@HotThoughts will look into it!

2021-05-02 12:30 UTC, twerkmeister requested changes
Very cool, good find and thanks for taking the initative on this one 👍 ! Just added small suggestions that you can use directly.

2021-05-02 12:30 UTC, twerkmeister commented on changelog/7005.bugfix.md
> +Add encoding ´utf-8´ to write_dot funcion
As this goes into a big change log file, the following gives a bit more context:
```suggestion
Fixed a bug for plotting trackers with non-ascii texts during interactive training by enforcing utf-8 encoding
```

2021-05-02 12:30 UTC, twerkmeister commented on rasa/core/training/interactive.py
> +    output_file.close()
Doesn't override existing variable, briefer, no closing necessary:
```suggestion
    with open(output_file, "w", encoding="utf-8") as f:
        write_dot(graph, f)
```

2021-05-02 19:50 UTC, joaoCeilandia commented
Thanks for the feedback @twerkmeister !

2021-05-03 05:23 UTC, twerkmeister approved these changes
👍

2021-05-03 05:25 UTC, merged