add log time rotating handle
RasaHQ/rasa pull request #8473
Opened 2021-04-15 04:29 UTC by HatuneMiku

**Proposed changes**:
- ...

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/main/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

The log of `rasa run` will become larger and larger with the increase of time, and it is necessary to divide it in actual production. The custom component part can be implemented by your own code, but the log of the core part is always written in a file by default. This change only adds the option of converting by time.

2021-04-15 06:00 UTC, sara-tagger commented
Thanks for submitting a pull request 🚀 @melindaloubser1 will take a look at it as soon as possible ✨

2021-04-26 15:46 UTC, joejuzl requested changes
Thanks for this!

2021-04-26 15:46 UTC, joejuzl commented on rasa/cli/arguments/run.py
> +        # Rasa should not rotaing log file by default
```suggestion
        # Rasa should not rotate log files by default
```

2022-02-22 11:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RasaHQ/rasa?pullRequest=8473) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/RasaHQ/rasa?pullRequest=8473) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: XiaofeiQian<br/>:x: Hsiaofei Tsien<br/><hr/>**Hsiaofei Tsien** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RasaHQ/rasa?pullRequest=8473) it.</sub>

2022-02-23 02:05 UTC, closed without merging