8461 non expressive variable name
RasaHQ/rasa pull request #8504
Opened 2021-04-19 18:47 UTC by joaoCeilandia

**Proposed changes**:
-fix #8461 

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/main/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

2021-04-21 19:44 UTC, ArjaanBuijk commented on rasa/utils/tensorflow/transformer.py
> +        array_2D = np.arange(self.units)[np.newaxis, :]
please use all lowercase: `array_2d`

2021-04-21 19:44 UTC, ArjaanBuijk commented on rasa/utils/tensorflow/transformer.py
> +        return 1 / np.power(10000, (2 * (array_2D // 2)) / np.float32(self.units))
please use all lowercase: `array_2d`

2021-04-21 19:45 UTC, ArjaanBuijk requested changes
To be pep8 compliant, please use all lowercase for the new variable name.

2021-04-21 23:41 UTC, joaoCeilandia commented on rasa/utils/tensorflow/transformer.py
> +        return 1 / np.power(10000, (2 * (array_2D // 2)) / np.float32(self.units))
ok

2021-04-21 23:41 UTC, joaoCeilandia commented on rasa/utils/tensorflow/transformer.py
> +        array_2D = np.arange(self.units)[np.newaxis, :]
ok

2021-04-26 17:42 UTC, ArjaanBuijk approved these changes
Thank you!

2021-04-27 13:52 UTC, ArjaanBuijk commented
@joaoCeilandia ,
All is ready to be merged, but your branch is out-of-date with the base branch, so I cannot merge it.
Can you please update the branch in your fork, or make your branch writeable for me?

2021-04-30 20:26 UTC, joaoCeilandia commented
Has no conflicts with the base branch now.  I don't know if i can make my branch writeable for you because it is from a class in my college. @ArjaanBuijk

2021-05-03 13:10 UTC, ArjaanBuijk commented
@joaoCeilandia ,
Can you bring your branch up-to-date with the base branch again?

sorry it has to be done this way, but if you are not able to make your branch writeable for me, you will have to update it manually again.

Things are added quickly, and your PR is in the queue to be merged in, but it needs to be squeezed in there.

2021-05-03 13:36 UTC, merged

2021-05-04 10:50 UTC, ArjaanBuijk commented
@joaoCeilandia ,
thanks for the PR!