Intent ted policy default
RasaHQ/rasa pull request #8748
Opened 2021-05-26 12:46 UTC by alwx

**Proposed changes**:
- fix #8415 

_**!!! https://github.com/RasaHQ/rasa/pull/8555 needs to be merged first!**_

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [x] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/main/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

2021-06-09 15:09 UTC, wochinge requested changes

2021-06-09 15:09 UTC, wochinge commented on rasa/shared/importers/default_config.yml
> +  - name: IntentTEDPolicy
Let's keep `TEDPolicy` 🙂

2021-06-15 08:15 UTC, wochinge requested changes
Now it's missing from `rasa.shared.importers.default_config.yml`, isn't it?

2021-06-15 11:24 UTC, wochinge approved these changes
Did you double check the policy's default params with Daksh/Chris? Looks good to me otherwise 👍🏻

2021-06-15 11:29 UTC, dakshvar22 commented on data/test_config/config_empty_en_after_dumping.yml
> +#     constrain_similarities: true
Don't need `constrain_similarities` to be set to `true` for `IntentTEDPolicy`.

2021-06-15 11:35 UTC, dakshvar22 commented on data/test_config/config_empty_en_after_dumping.yml
> +#     constrain_similarities: true
In fact, it doesn't even exist in the available configuration parameters.

2021-06-15 11:50 UTC, merged