[CI] fix flakey CI
RasaHQ/rasa pull request #8884
Opened 2021-06-15 11:39 UTC by HotThoughts

**Proposed changes**:
- Upgrade actions/setup-python to v2.2.2

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/main/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

2021-06-16 06:51 UTC, tczekajlo requested changes

2021-06-16 06:51 UTC, tczekajlo commented on .github/workflows/ci-docs-tests.yml
> +      uses: actions/setup-python@dc73133d4da04e56a135ae2246682783cc7c7cb6  # v.2.2.2
```suggestion
      uses: actions/setup-python@dc73133d4da04e56a135ae2246682783cc7c7cb6  # v2.2.2
```

The same thing in the rest of places

2021-06-17 14:56 UTC, HotThoughts commented on .github/workflows/ci-docs-tests.yml
> +      uses: actions/setup-python@dc73133d4da04e56a135ae2246682783cc7c7cb6  # v.2.2.2
🕺 Fixed

2021-06-18 09:05 UTC, tczekajlo approved these changes
LGTM 🎖️

2021-06-18 09:05 UTC, merged