Update how-to-deploy.mdx
RasaHQ/rasa pull request #9087
Opened 2021-07-09 14:41 UTC by simon-kloker

the branch for repository RasaHQ/action-server-gha should now be main (currently: master)

**Proposed changes**:
- ...

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/main/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

2021-07-09 14:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RasaHQ/rasa?pullRequest=9087) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RasaHQ/rasa?pullRequest=9087) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RasaHQ/rasa?pullRequest=9087) it.</sub>

2021-07-12 06:00 UTC, sara-tagger commented
Thanks for submitting a pull request 🚀 @joejuzl will take a look at it as soon as possible ✨

2021-07-12 12:22 UTC, joejuzl requested changes
Thanks for this! Could you please add a changelog entry?

2021-07-12 12:22 UTC, joejuzl commented on docs/docs/how-to-deploy.mdx
>        # Full list of parameters: https://github.com/RasaHQ/action-server-gha/tree/master#input-arguments
Looks like there's a couple other uses of `master` in the file, could you change them too?

2021-07-12 13:22 UTC, closed without merging