Update 2.x with changes from 2.2.x
RasaHQ/rasa pull request #9368
Opened 2021-08-17 08:03 UTC by m-vdb

## Description

The goal of this PR is to show how changes made in a minor version would be documented in a "Docs for major only" setup. More information in [this document](https://www.notion.so/rasa/Doc-versions-for-Majors-only-caaf78eadff34d7d8b49eb2284ccc8f9).

## How to use this PR
- you can run do `cd docs && yarn && yarn develop` to run the docs locally
- skip `changelog.mdx`
- skip `sources/` and `reference/` folders
- look at different kind of changes:
  - changes introduced in the docs because there were changes in the codebase (new feature, changes in behaviour, deprecations)
  - changes in the docs to improve it, independent of codebase change
 
<details><summary>💡 Pro-tip, filter files in the PR on ".mdx" only</summary>
<img width="312" alt="Screenshot 2021-08-05 at 13 48 11" src="https://user-images.githubusercontent.com/1931615/128345065-6b965241-182a-4fc5-89aa-0d8868162c88.png"></details>

## Next steps
- [ ] get reviews
- [ ] remove the 2.2.x version of the docs in this branch
- [ ] merge this branch into `documentation-full`
- [ ] repeat the process for all minors until 2.8

2021-08-17 08:24 UTC, m-vdb commented
@desmarchris I went ahead and merged 2.2.x and 2.3.x in this PR. Can you take a look when you have the chance? Changes were easier to make this time, so I did 2 versions in a row

2021-08-17 20:23 UTC, desmarchris requested changes

2021-08-17 20:23 UTC, desmarchris commented on docs/versioned_docs/version-2.x/nlu-only-server.mdx
> +The `token` and `token_name` refer to optional [authentication paramenters](./http-api.mdx#token-based-auth).
```suggestion
The `token` and `token_name` refer to optional [authentication parameters](./http-api.mdx#token-based-auth).
```

2021-08-17 20:24 UTC, desmarchris commented
looks good!

2021-08-18 08:34 UTC, m-vdb commented
@desmarchris probably a good idea to approve the changes if the requested changes are minor. That way I can incorporate the changes and then merge the PR without overriding your change request (here I assume that everything is good apart from the minor change). Not a big deal :)

2021-08-18 08:39 UTC, merged