Adapt `FallbackClassifier` to graph component interface
RasaHQ/rasa pull request #9559
Opened 2021-09-07 09:15 UTC by ancalita

**Proposed changes**:
- Closes #9409 

**Status (please check what you already did)**:
- [X] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/main/changelog) for instructions)
- [X] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

2021-09-07 12:50 UTC, joejuzl requested changes

2021-09-07 12:50 UTC, joejuzl commented on rasa/nlu/classifiers/_fallback_classifier.py
> +#          `rasa.nlu.classifiers.sk_learn_intent_classifier` module.
```suggestion
#          `rasa.nlu.classifiers.fallback_classifier.py` module.
```

2021-09-07 12:50 UTC, joejuzl commented on rasa/nlu/classifiers/fallback_classifier.py
> +        self._execution_context = execution_context
I don't think we need any of these.

2021-09-07 12:50 UTC, joejuzl commented on tests/nlu/classifiers/test_fallback_classifier.py
> +    classifier = FallbackClassifierGraphComponent.create(
We could extract a helper to create the component?

2021-09-07 15:59 UTC, aeshky approved these changes
Looks good to me.

2021-09-08 07:29 UTC, joejuzl approved these changes
💯

2021-09-08 07:59 UTC, merged