Update the docs
RasaHQ/rasa pull request #9608
Opened 2021-09-10 14:33 UTC by tczekajlo

**Proposed changes**:
- Update documentation related to the installation methods 

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/main/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

2021-09-14 12:46 UTC, tczekajlo commented
@TyDunn @melindaloubser1 Here are changes related to the rasa docs, a summary for the changes:

- The rasa helm chart is the only recommended installation method for production.

The changes mostly drop other installation methods and add several links to the Rasa X docs where are the biggest changes.

Please go through it and share your thoughts 🙏🏻 , is there something that should be added, is something missing?

2021-09-27 14:32 UTC, tczekajlo commented
> you need to deploy your assistant with the Rasa Open Source Helm Chart, deploy Rasa X with its own Helm Chart, and then forward events, correct?

@TyDunn answering your question and moving the conversations here.

Yes, pretty much it's what has to be done to connect Rasa OSS deployment with Rasa X deployment.

2021-09-30 05:04 UTC, rgstephens reviewed
@tczekajlo Take a look at my re-write and consolidation of the first paragraph and let me know what you think. I think it would be great if we can describe use of REI for a Rasa OSS install and recommend that as an alternative to docker-compose. Do you think there is time to write that up?

2021-09-30 13:37 UTC, tczekajlo commented
> @tczekajlo Take a look at my re-write and consolidation of the first paragraph and let me know what you think. I think it would be great if we can describe use of REI for a Rasa OSS install and recommend that as an alternative to docker-compose. Do you think there is time to write that up?

@rgstephens Thanks a lot for reviewing 🙏🏻  The first paragraph looks good to me 👍🏻 

I think we got some extra time 😄  I've created a separate page that describes how to deploy Rasa OSS by using REI and I included it in the "Alternatives deployment methods". Additionally, the document/page says that we recommend it as an alternative to docker-compose.

WDYT?

2021-09-30 14:05 UTC, TyDunn commented
@tczekajlo @rgstephens  I think we need to make this page more clear and nudge user towards Rasa X more. 

I chatted with @rugging24 about this, and this is what we came up with for a potential high level structure of this page:

(Paragraph about building a minimum viable assistants)
1. Deploy Rasa Open Source helm chart
2. Deploy action server helm chart
3. Create connection with action server
4. Deploy Rasa X helm chart
5. Forward events from Rasa Open Source to Rasa X

Wdyt of this?

2021-09-30 14:11 UTC, TyDunn commented on docs/docs/how-to-deploy.mdx
>  How you reference the custom action image will depend on your deployment. Pick the relevant documentation for
The action server docs need to be clear about how you use the action server with the open source helm chart imo

2021-10-01 08:00 UTC, tczekajlo commented
> @tczekajlo @rgstephens I think we need to make this page more clear and nudge user towards Rasa X more.
> 
> I chatted with @rugging24 about this, and this is what we came up with for a potential high level structure of this page:
> 
> (Paragraph about building a minimum viable assistants)
> 
> 1. Deploy Rasa Open Source helm chart
> 2. Deploy action server helm chart
> 3. Create connection with action server
> 4. Deploy Rasa X helm chart
> 5. Forward events from Rasa Open Source to Rasa X
> 
> Wdyt of this?

Looks good to me. I think we miss a part related to the action server. I'll add missing parts.

2021-10-01 12:19 UTC, tczekajlo commented
I've reorganized a bit the "Deploying Your Assistant" section and I added things that we talked about in the previous comments.

@TyDunn @rgstephens  Can you 👀  if you have a minute and share your thoughts?

2021-10-02 07:11 UTC, TyDunn requested changes
@tczekajlo This is starting to really take shape! I focused on structure again. I like how you broke it into sections. I want to make that even more clear and explicit...

*Preparing For Production*

Deploying Your Assistant

Step 1: Deploy Rasa Open Source
  a. Set up Rasa Open Source deployment

Step 2: Deploy Action Server
  a. Set up Action Server deployment
  b. Connect Action Server to Rasa Open Source deployment 

Step 3: Deploy Rasa X
  a. Set up Rasa X deployment
  b. Connect Rasa X to Rasa Open Source deployment
  
 **Can we maybe even add this table of contents (with links) to the Introduction section?**

2021-10-02 07:11 UTC, TyDunn commented on docs/docs/deploy/deploy-rasa.mdx
> +description: How to deploy your Rasa Assistant with Kubernetes/Openshift
```suggestion
description: The first of three steps to deploy your Rasa assistant
```

2021-10-02 07:11 UTC, TyDunn commented on docs/docs/deploy/deploy-rasa.mdx
> +abstract: This page explains how to deploy Rasa Assistant by using Helm.
```suggestion
abstract: This page explains how to deploy Rasa Open Source using Helm. The first of three steps in deploying your Rasa assistant.
```

2021-10-04 09:39 UTC, tczekajlo commented on docs/docs/deploy/deploy-rasa-x.mdx
> +Visit the [Connect Rasa Open Source deployment](https://rasa.com/docs/rasa-x/installation-and-setup/deploy#2-connect-rasa-open-source-deployment-the-rasa-helm-chart) section to learn how to connect y
Yes, exactly.

2021-10-04 09:40 UTC, tczekajlo commented on docs/docs/deploy/deploy-rasa-x.mdx
> +Visit the [Installation Guide for Rasa X](https://rasa.com/docs/rasa-x/installation-and-setup/installation-guide) where you can learn about available installation methods and
It points to the page which describes available installation methods for Rasa X.

2021-10-06 07:55 UTC, melindaloubser1 commented
One note: We should link to the action server deployment instructions from the Rasa SDK docs

2021-10-08 10:10 UTC, tczekajlo commented
> One note: We should link to the action server deployment instructions from the Rasa SDK docs

Sounds good to me, @TyDunn WDYT about moving the section related to the Action sever deployment to the Rasa SDK docs?

2021-10-08 10:16 UTC, TyDunn commented
> WDYT about moving the section related to Action Server deployment to the Rasa SDK docs?

Sounds good to me

2021-10-12 09:51 UTC, tczekajlo commented
@rgstephens @TyDunn Can you give it another look if you have a minute? 🙏🏻  Is there anything else to improve/change or we are good here?

2021-12-06 13:53 UTC, merged